### ISSUE TITLE
Please port the latest version to Forge 1.19.2

### ISSUE THREAD

**Issue by kitovoi111** [Wesley1808/ServerCore#111]
Please port the latest version to Forge 1.19.2
I have a large server on Forge 1.19.2 with IC2 classic mod, which is only available on 1.19.2, I need the latest innovations in your mod for 1.19.2, please.

**Comment by Wesley1808** [comment]
Is there anything specific you need or is it just in general? 1.19.2 is getting pretty old by now, I don't really have much motivation or time to backport everything to it.

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/72e818af-4c7b-46bc-a224-10758f0cf8d7)

**Comment by kitovoi111** [comment]
> https://github.com/Wesley1808/ServerCore/actions/runs/10250906910 _should_ probably work for that, backporting a version of the mobcap config I made just before the config switch.

Thank you very much. You are my savior.

**Comment by kitovoi111** [comment]
> https://github.com/Wesley1808/ServerCore/actions/runs/10250906910 _should_ probably work for that, backporting a version of the mobcap config I made just before the config switch.

Here's a question. Can you please add a per-player-mob-spawn function to servercore?

**Comment by kitovoi111** [comment]
> > https://github.com/Wesley1808/ServerCore/actions/runs/10250906910 _should_ probably work for that, backporting a version of the mobcap config I made just before the config switch.
> 
> Here's a question. Can you please add a per-player-mob-spawn function to servercore?

https://modrinth.com/mod/fabric-per-player-spawns

**Comment by kitovoi111** [comment]
Since the usual mob spawn is very bad and there are almost no mobs on the map, if the mob-cap is 10-30%, and if you add per-player-mob-spawn - then there will always be a lot of mobs since they spawn around the player. Considering the simulation.

**Comment by Wesley1808** [comment]
Per player mobspawning has been in the vanilla game since like 1.18. If that mod makes mobs spawn more frequently than without it, its because of some other behavior change it does. Which is a bit out of scope for servercore.

**Comment by Wesley1808** [comment]
I would suggest checking the global mobcaps to see if they're not full (mods like carpet mod can do this), sometimes one area can fill up the global cap with non-despawnable mobs that still count to the mobcap (for example mob switches).

Its possible that per player spawns mod completely skips the global mobcap, but idk that for sure. Otherwise make sure to check with `/mobcaps` that the cap just isn't already full at 10-30%, which can happen fairly quickly. If it is full then its intentional behavior that it doesn't spawn more than its supposed to.

**Comment by kitovoi111** [comment]
Ender mobs very more spawn rate in mob-caps: 20.
![image](https://github.com/user-attachments/assets/985929a4-d64d-459b-9566-bcdeae1af6d9)

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/116a1ff8-c211-4b18-a5ad-b5e40da275e0)

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/e71d4800-4933-43f5-9e11-eccc25b0ea43)

**Comment by Wesley1808** [comment]
None of those mobs are counting towards the mobcap at all? Servercore doesn't change how mobs are counted towards the mobcap. Mobcaps are a vanilla feature, servercore only gives the option to modify the maximum capacity, which is the second number on that screen - which looks correct.

If mobs aren't counting to the cap and you think they should be that is most likely the fault of the mod that implements those mobs, as there's a high chance you will find them not counting to the mobcap without servercore (you would just need some alternative way to inspect the mobcap)

**Comment by kitovoi111** [comment]
creatures 2500/1

**Comment by Wesley1808** [comment]
Those end mobs are from the creature mobcap? Did you change the spawn interval by chance? Creature spawns are supposed to be much slower than everything else, with their interval at 400.

If thats the case it still wouldn't explain why it would overspawn those mobs, does the same thing happen with cows, chickens and pigs?

**Comment by kitovoi111** [comment]
The problem is in the new version of the mod. Please check yourself, I don't quite understand. mod Endergetic (Abnormals team)

**Comment by Wesley1808** [comment]
I've figured out the absurdly fast spawning, but the spawning-over-mobcap is technically still possible.
The reason behind this is because Endergetic uses a custom mobcap `ender_creature` for spawning, but gives the mobs itself the vanilla `creature` mobcap. This means that the `ender_creature` mobcap will always have room to spawn more mobs, allowing spawning, while adding them to another cap. This is much less noticeable without the really fast spawning though.

**Comment by kitovoi111** [comment]
thank you very much!

**Comment by Wesley1808** [comment]
This version is now released on curseforge and modrinth as 1.3.6+1.19.2
