### ISSUE TITLE
activation-range reduces the efficiency of iron farm

### ISSUE THREAD

**Issue by ifloppy** [Wesley1808/ServerCore#118]
**Describe the bug**

When the `activation-range` is enabled, the efficiency of the iron farm significantly decreases, resulting in fewer or even zero iron golems being spawned by villagers. This issue persists even when `minecraft:villager` and `minecraft:pillager` are included in the `excluded-entity-types`.

This is the basic structure of the iron farm:

![image](https://github.com/user-attachments/assets/d4bce890-a965-451d-8515-eaf893bd72a9)

**To Reproduce**

1. Enable the `activation-range` (default setting).
2. Observe the iron farm's efficiency.

**Expected behavior**

The iron farm should maintain its normal efficiency, with villagers consistently spawning iron golems.

**Versions**
- ServerCore: 1.5.5
- Minecraft: 1.21.1

**Mod incompatibilities**

None. The iron farm operates with normal efficiency without ServerCore.

**Comment by Wesley1808** [comment]
With activation range on and not being excluded this is more or less expected behavior. There are some checks in place to make them still work *most* of the time for most iron farms, but results are dependent on the farm design used. This one moves the pillager around a lot meaning there's a good chance the villagers won't detect it and be immunized by it before its gone again.

Now when villagers are added to excluded entity types, thats where this gets strange. Did you make sure to /sc reload to reload the config file and then unload -> reload the area (or world) before checking if it changed anything? Some changes like these need the entities themselves to be reloaded.

If that doesn't work, try to add minecart to it aswell just to be sure that isn't affecting it.

**Comment by ifloppy** [comment]
It works now. Thank you!

Reloading the chunk resolved the issue with the exclusion of villagers.
