### ISSUE TITLE
Servercore is incompatible with any version of Cardboard

### ISSUE THREAD

**Issue by LazyAtArt** [Wesley1808/ServerCore#21]
Servercore has a compatibility issue with Cardboard: a mod that allows minecraft servers to use mods and plugins at the same time. You can recreate the issue by trying to use them both on the server. 

[logs_latest.log](https://github.com/Wesley1808/ServerCore/files/8187757/logs_latest.log)

**Comment by Wesley1808** [comment]
Cardboard is marked as incompatible because it breaks this mod entirely (and a massive amount of other fabric mods aswell).

You can disable this check using a dependency override - more information about it [here](https://fabricmc.net/wiki/tutorial:dependency_overrides) - but from my knowledge it would crash at startup anyway.

I won't be supporting cardboard, due to its very invasive behavior that already breaks vanilla itself.
More information on this topic: https://gist.github.com/Patbox/e44844294c358b614d347d369b0fc3bf
