### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nikijaz** [Wesley1808/ServerCore#48]
**Describe the bug**
There was one unexpected crash. It was not connected to anything, it just happened and that's all.
https://mclo.gs/ySNfcjL

**Reproduce**
Unfortunately, I do not have them, because the crash happened for the first time and as unexpectedly as possible.

**Expected behavior**
Crash does not happen.

**Versions** -Latest is not a version!
ServerCore: 1.3.1-1.19.1
Minecraft: 1.19.2

**Mod incompatibilities**
No ideas at all.

**Comment by Wesley1808** [comment]
I'm not sure what could cause this issue. I highly doubt its related to ServerCore though. The only reason it shows up in the stacktrace is because `servercore$shouldTickEntity()` wraps `Entity#tick()` which means it will basically exist in all entity ticking crash stacktraces (but almost never be related).

**Comment by nikijaz** [comment]
Okay, very strange. It happened for the first time, and in a very long time of using all the mods. I'll watch then, but for now, closing issue.
