### ISSUE TITLE
Chunk ticking distance A setting that allows you to reduce the distance at which chunks can tick (mob spawns & random ticks). This allows for higher viewdistances at lower costs.

### ISSUE THREAD

**Issue by MounBrowt** [Wesley1808/ServerCore#50]
This option serves as an alternative to the FeatherViewDustance plugin on Spigot?

**Comment by MounBrowt** [comment]
![image](https://user-images.githubusercontent.com/116191734/197391556-326fe227-f3bd-4ad2-a154-bf36b1e23dcd.png)

**Comment by MounBrowt** [comment]
And in server.properties you have to put for example 20 chunks, and the load will be the same as with 10?

**Comment by MounBrowt** [comment]
@Wesley1808

**Comment by Wesley1808** [comment]
I wouldn't say its similar to FeatherViewDistance - the only thing it does is keep chunks outside of that radius from being ticked (which includes: natural mobspawning and random ticks).

The load at 20 chunks viewdistance and 10 chunk-tick distance won't be the same as 10. It still needs to load all those chunks and keep them in memory. 

A chunk tick distance above 10 won't do much anyway because vanilla already filters out any chunks that are far enough away (anything further than about 8-9 chunks). This setting more or less just adds to that filter. I figured that part out just a while ago though, that text has been there for much longer - and I might want to change it.

**Comment by MounBrowt** [comment]
I honestly almost didn't understand it)

**Comment by MounBrowt** [comment]
I might have understood, but I don't speak English. Thanks for the answer anyway.
