### ISSUE TITLE
Bits and chisel blocks appear invisible when severcore is enabled, until you chisel something.

### ISSUE THREAD

**Issue by netcore10** [Wesley1808/ServerCore#53]
**Describe the bug**
Bits and chisel blocks appear invisible when severcore is enabled. Not sure why.
**Reproduce**
install bits and chisels
install servercore
chisel a block and restart.
once joined, bits and chisel blocks appear invisible until you chisel something.

**Expected behavior**
No invisible chisel blocks

**Versions** -Latest is not a version!
ServerCore:1.3.3
Minecraft:1.19.2

**Mod incompatibilities**
starlight?
Thicc packets?
Bits and chisels

**Comment by Wesley1808** [comment]
I can't seem to reproduce this. Are you sure this is in any way related to servercore?
If so, would you mind also sending your configs? (for servercore and bits-and-chisels if it has one)

Also, does this happen even if servercore is *not* installed on the client? Cause this seems like a rendering issue and if that were the case I would be really confused 😆

**Comment by netcore10** [comment]
It doesn't happen if servercore is disabled. Though i forgot to mention i have the sodium getup, but i tested without them too. Aside from that, bit's and chisels doesn't really have a config. It's a very odd issue. The moment server core was enabled, bit blocks start invisible until you edit one.

**Comment by netcore10** [comment]
> It doesn't happen if servercore is disabled. Though i forgot to mention i have the sodium getup, but i tested without them too. Aside from that, bit's and chisels doesn't really have a config. It's a very odd issue. The moment server core was enabled, bit blocks start invisible until you edit one.

i essentially slimmed down to try and find the issue, but servercore seemed to be the thing effecting it.

**Comment by Wesley1808** [comment]
To narrow it down a bit, could you provide servercore's config file `servercore.toml` and give me a better idea of the exact setup you're using? Such as:
- Does this only happen if servercore is installed on the client?
- Does this happen in singleplayer too, or just dedicated server / client setup. If so, do both client and server have servercore installed? etc.
- Which version of Bits and Chisels are you using?
- Are there any other mods installed besides the 3 you listed?

Would at least make it so I don't have to try out 20 different combinations trying to reproduce it.

**Comment by netcore10** [comment]
Sorry, shoulda clarified with a modlist. I slimmed down quite a bit, but here's the config, it's on server side only, because i figured a mod named "Server core" only needed server side. As for my mods, i can just send the server log so you can see the modlist and what launches, it's not public yet. There were more than i expected though. 
[logs_latest.log](https://github.com/Wesley1808/ServerCore/files/9939767/logs_latest.log)

[config_servercore.txt](https://github.com/Wesley1808/ServerCore/files/9939746/config_servercore.txt)

**Comment by Wesley1808** [comment]
> Sorry, shoulda clarified with a modlist. I slimmed down quite a bit, but here's the config, it's on server side only, because i figured a mod named "Server core" only needed server side.

You're right about that, but some also install it on the client since it works on singleplayer (internal servers) aswell. As this seems like it would have to be a rendering issue, I am rather confused how a mod not touching anything remotely close to modifying packets or rendering could cause this to happen on a client that doesn't even have it.

So just to make sure, I really can't seem to get this to work (thicc packets, starlight, quilt instead of fabric - results are the same),
Your reproduction steps are:
1. Install both mods
2. Chisel any random block
3. Restart the server
4. Join back and all blocks that were chiseled *should* be (but for me isn't) invisible until you try to chisel something?

**Comment by netcore10** [comment]
indeed that is correct, when i join my server with server core on, after a restart it seems to make chiseled blocks invisable until you chisel any block. When servercore is disabled, it never happens.

**Comment by netcore10** [comment]
> indeed that is correct, when i join my server with server core on, after a restart it seems to make chiseled blocks invisable until you chisel any block. When servercore is disabled, it never happens.

could it's implimentation be expecting different ticking behavior or something?

**Comment by Wesley1808** [comment]
Very strange. I would have to assume it has to be some other mod in that list thats somehow silently conflicting with it (but even then this is an extremely weird issue). If you have the time to try to debug it, would you mind trying to reproduce it with __just__ servercore + bitsandchisels + quilted fabric api? 

Asking this mostly because its extremely inconvenient and time-wasting to have to find every mod in that list and manually download it. There are quite a few of them. If it somehow still happens after that, I have no idea what could cause that.

**Comment by netcore10** [comment]
What a weird issue! It's not crashing, so for now, i'll close this issue and try to do some investigating later on and reopen if i find anything!
