### ISSUE TITLE
Config gets reset to default after every reboot

### ISSUE THREAD

**Issue by thehobojoe** [Wesley1808/ServerCore#56]
**Describe the bug**
Any time the server or client restarts, the config resets to default.

**Reproduce**
Simply restart the server or client with any config edits.

**Expected behavior**
Config retains changes.

**Versions** -Latest is not a version!
ServerCore: 1.3.3
Minecraft: 1.19.2
On Fabric

**Mod incompatibilities**
List any installed mods you think might play a role in causing this bug.

**Comment by Wesley1808** [comment]
Is the server turned on when you are changing config values? And do you restart it after that without reloading the config?
`/sc config reload`

Because you can also change the config settings ingame using `/sc config <args>`, ServerCore saves the __ingame__ config values to the config file upon server shutdown. If you didn't reload it to load the values from config -> server then those ingame values will remain whatever they were when you started up the server.

If that doesn't help, could you send over the log file of when the server starts up after changing values? It resets entries to default if the input value is invalid, but that would be logged in the console. Most config options can also be reloaded on the fly and don't need the server to restart to take affect, excluding the optimizations tab and disable_spawn_chunks.

**Comment by thehobojoe** [comment]
I thought it wasn't, but I must have not been careful enough 😅 

Pulling in the config while running with `/sc config reload` seems to have fixed the problem, thank you!
