### ISSUE TITLE
Crash with Suggestion Tweaker

### ISSUE THREAD

**Issue by SplendidAlakey** [Wesley1808/ServerCore#59]
**Describe the bug**

After updating ServerCore to 1.3.5, the game crashes on startup, if [Suggestion Tweaker](https://www.curseforge.com/minecraft/mc-mods/suggestion-tweaker) is also installed.

Rolling back to 1.3.3 lets the game start, hence reporting here.

**Reproduce**

1. Install ServerCore 1.3.5 and [Suggestion Tweaker](https://www.curseforge.com/minecraft/mc-mods/suggestion-tweaker)
2. Run the game

**Expected behavior**

No crash.

**Versions** -Latest is not a version!

ServerCore: 1.3.5
Minecraft: 1.19.2

**Mod incompatibilities**

[Suggestion Tweaker](https://www.curseforge.com/minecraft/mc-mods/suggestion-tweaker)

Logs: https://gist.github.com/SplendidAlakey/c088c34100a65ccfbe609f794c3400b5

**Comment by Wesley1808** [comment]
Hey, thanks for reporting this issue. It seems to happen because of the new multi-platform setup, and some platform specific methods need to be loaded before mixin loads to load the config and check for other mods being loaded.

There are a few platform-specific methods using minecraft classes in there aswell though, and even if they aren't actually used until later java will load them immediately, causing any mods mixing into them to crash. Will probably have to look into splitting up the platform specific methods to fix this.

**Comment by Wesley1808** [comment]
Would you be able to try out the development build listed [here](https://github.com/Wesley1808/ServerCore/actions/runs/4677101489) to see if the issue still persists?
In my testing it works properly, at least in dev environment. If it works I'll be pushing this to all the other branches aswell.

**Comment by SplendidAlakey** [comment]
Yep, that works, thank you!
