### ISSUE TITLE
BlockGetterMixin class has invalid @Redirect signature when paired with Exordium

### ISSUE THREAD

**Issue by owosoup** [Wesley1808/ServerCore#70]
**Describe the bug**
Using Quilt loader, the mod crashes the game during mixins. 

_Full crash log:_
pastebin.com/qfCYuCzz

**Reproduce**
Use the Quilt loader, and the Exordium mod (modrinth.com/mod/exordium).
Use Servercore as well.

**Expected behavior**
Minecraft starts and I enjoy my lag free world with less ticking.

**Versions**
ServerCore: 1.3.5
Minecraft: 1.19.4
Exordium: 1.1.2

**Mod incompatibilities**
Exordium.

**Comment by Wesley1808** [comment]
Thanks for reporting this. It looks like the loader is confused on which version of MixinExtras to use, as both ServerCore and Exordium include different versions of it in the mod jar. Some of the features in newer versions of it are used for that mixin.

Normally speaking it should just choose the one with the highest version number, which seems to be indicated by the logs - but for some reason its still messing with it, because when I remove MixinExtras from Exordium's jar file everything works as expected.

**Comment by owosoup** [comment]
I'll report it to the other project!
