### ISSUE TITLE
/servercore settings command not working in game

### ISSUE THREAD

**Issue by envagyokte** [Wesley1808/ServerCore#73]
**Describe the bug**
In game the command simply not existing. For example the in game /servercore status is working, while /servercore settings is not even shows up nor working.

**Reproduce**
BMC 3 curse forge server. 
start the server 
join
try to use the command: /servercore settings

**Expected behavior**
the command should allow me modifying settings & configs ingame
**Versions** 
ServerCore: 1.3.5
Minecraft: 1.19.2

**Mod incompatibilities**
Uisng BMC 3 Modpack but I dont know about any exact mod that could be a problem.

**Comment by Wesley1808** [comment]
`/servercore settings` by itself isn't a completed command. You need to specify which setting you want to change and what value to change it to. Ingame command suggestions will help you with this.

Note that this doesn't let you modify the configs - thats what `/servercore config` is for, where the same rules apply.

Example (settings): `/servercore settings view_distance 12`
Example (config): `/servercore config features lobotomize_villagers true`

**Comment by envagyokte** [comment]
Thank you for the fast respond!
I'm sure I'm too underqualifed to use the commands poperly.
The view distance command, the one that you made an example with did not work in game. But worked in the server control panel.
My goal is to turn mob_cap off or to set the animals cap higher then 24. If you could just tell me the needed command I would be greatful. 
I attached some screenshot so you can see what i'm doing.

![image](https://github.com/Wesley1808/ServerCore/assets/143231655/7ba220c0-b7ad-4c38-a5a1-7a5ddd95d5a5)
![image](https://github.com/Wesley1808/ServerCore/assets/143231655/f0679d86-a94c-4741-ad9a-e143b2130b28)
![image](https://github.com/Wesley1808/ServerCore/assets/143231655/19765875-6fbc-4d00-8250-2338d3710e68)

**Comment by Wesley1808** [comment]
If the commands don't work ingame, thats likely due to your player not having sufficient permissions to use it.
If you have to use the console to use the commands anyway, you should just edit the config file `/config/servercore.toml` directly and run `/sc config reload` in the console.

The /sc (redirect for /servercore) config commands are based on the [config](https://github.com/Wesley1808/ServerCore#config) itself. Therefore changing breeding_cap would be
`/sc config breeding_cap enabled false`, not `/sc config features breeding_cap false`.

But if you have to use console, where you have no command suggestions, it will be much easier to just edit the config file directly and run that one command to load the changes into the game.

**Comment by envagyokte** [comment]
Oh yeah. Giving myself OP did help a lot. And I didn't know that i should use config reload after edited the configfile..
It seems like its working now. Thanks a lot!
